pkblogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'))
]

posts/urls.py
from django.urls import path
from .views import index, post_details

app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('post/<int:year>/<int:month>/<int:day>/<slug:post_slug>', post_details, name='details')
    # path('post/<slug:post_slug>', post_details, name='details')
    # path('post/<int:post_id>', post_details, name='details')
]

posts/models.py
from django.db import models
from django.db.models import Model
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.


class Post(models.Model):
    STATUS_CHOICES = (
        ('DRAFT', 'Draft'),
        ('PUBLISHED', 'Publish')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='DRAFT')

    class META:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    @classmethod
    def total_posts(cls):
        total = Post.objects.count()
        return total

    @classmethod
    def published_posts(cls):
        return cls.objects.filter(status='PUBLISHED')

    def save(self, *args, **kwargs):
        slug = slugify(self.title)
        self.slug = slug
        super().save(*args, **kwargs)


class Comment(models.Model):
    # id = models.AutoField(primary_key=True) --> This field is auto generated by Django
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    # post_id = models.IntegerField() --> This field is auto created after creating relation
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

posts/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Post

# Create your views here.


def index(request):
    # posts = Post.objects.filter(status='PUBLISHED')
    posts = Post.published_posts()
    total_posts = Post.total_posts()
    paginator = Paginator(posts, per_page=2)
    # get the page number from url, query parameter
    page_number = request.GET.get('page')
    # get all posts from that page number
    posts = paginator.get_page(page_number)
    return render(request, 'posts/index.html', context={'posts': posts, 'total_posts': total_posts})


def post_details(request, year, month, day, post_slug):
    post = Post.objects.get(publish__year=year, publish__month=month, publish__day=day, slug=post_slug, status='PUBLISHED')
    return render(request, 'posts/detail.html', context={'post': post})

posts/templates/posts/detail.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Index</title>
    <link href='{% static "css/style.css" %}' rel="stylesheet">
</head>
<body>
    <div id="content">
        <h1>{{ post.title }}</h1>
        <p class="date">Published {{post.publish}} by {{post.author}}</p>
        <h2>{{ post.body }}</h2>
        <a href="{% url "posts:index" %}" ><h2>Back</h2></a>
    </div>
    <div id="sidebar">
        <h2>pk blogs</h2>
        <p>Travel & share your Experiences</p>

    </div>
</body>
</html>

posts/templates/posts/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Index</title>
    <link href='{% static "css/style.css" %}' rel="stylesheet">
</head>
<body>
    <div id="content">
        {% for post in posts %}
        <a href="{% url "posts:details" year=post.publish.year month=post.publish.month day=


        post.publish.day post_slug=post.slug %}">
        <h2>{{ post.title}}</h2></a>
        <p class="date">Published {{post.publish}} by {{post.author}}</p>
        <p>{{post.body}}</p>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &laquo;</a>
            {% endif %}
        </span>

    </div>
    <div id="sidebar">
        <h2>demo blogs</h2>
        <p>Tech related blog</p>
        <p>Total Posts: {{ total_posts}}</p>

    </div>
</body>
</html>